### PR TITLE
Implemented legacy icsneoGetTimeStampForMsg() function call.

### PR DESCRIPTION
**Pull request by drebbe-intrepid**
See Issue #5 for more details.

### CODE REVIEW

**Comment by drebbe-intrepid** [comment]
Here is the python test script I used to test this. I used a neoVI FIRE2 and ValueCAN4.2. ValueCAN4.2 was transmitting HSCAN1 messages every 500ms.

I used the icsneolegacy.dll if running a 64-bit version of the interp and icsneo40.dll if using 32-bit.

```
import ics
import datetime
import time
import platform
import os

if '64' in platform.architecture()[0]:
    print("Using icsneolegacy.dll")
    ics.override_library_name(r"E:\development\libicsneo\Debug\icsneolegacy.dll")

if __name__ == "__main__":
    # Make sure we have at least one device attached
    for d in ics.find_devices():
        print(d, d.NumberOfClients)
    if not len(ics.find_devices()):
        print("Not enough devices...")
        exit(1)
    # Open the device
    print("Opening device...")
    d = ics.open_device()
    print ("Opened {} {}".format(d.Name, ics.base36enc(d.SerialNumber)))
    
    if '32' in platform.architecture()[0]:
        input("Press any key to continue... %d" % os.getpid())
    time.sleep(1.5)
    mult_10ns = 42949.67296
    mult_25ns = 0.000000025
    
    mult_1 = 0.000000025
    mult_2 = 107.3741824
    # parse all the messages
    msgs = ics.get_messages(d)[0]
    ep = datetime.datetime(2007, 1, 1, 0, 0, 0)
    x = (datetime.datetime.utcnow() - ep).total_seconds()
    print("{} seconds since epoch (1/1/2007)".format(x))
    for i, msg in enumerate(msgs):
        timestamp = ics.get_timestamp_for_msg(d, msg)
        #calculated = (msg.TimeHardware * mult_25ns) +  (msg.TimeHardware2 * mult_25ns)
        calculated = (msg.TimeHardware * mult_1) +  (msg.TimeHardware2 * mult_2)
        ts64 = msg.TimeHardware2 << 32
        ts64 += msg.TimeHardware
        ts64 /= 25
        print("{}.) [{}][{}]\tTimestamp: {}\t{}\t{}\t{}".format(i, hex(msg.ArbIDOrHeader), ', '.join([hex(x) for x in msg.Data]), timestamp, msg.TimeHardware, msg.TimeHardware2, ts64))
        print(msg.StatusBitField, msg.StatusBitField2, msg.StatusBitField3, msg.StatusBitField4)
    
    print("Done.")
        
```

**Comment by pierreluctg** [comment]
@drebbe-intrepid, this works perfectly for me on Ubuntu 16.04.6 64 bits.

Thank you

**Comment by pierreluctg** [comment]
Hi @hollinsky-intrepid do you have a ETA for merging this fix?

Thank you

**Comment by hollinsky-intrepid** [comment]
My apologies taking so long on this one. I want to take a closer look at the implementation and see if we can keep the timestamp multiplier out of the message structures. It's just a couple byte size penalty we probably don't need in a lot of cases.

**Comment by pierreluctg** [comment]
Hi @hollinsky-intrepid do you have an update to share?

**Comment by pierreluctg** [comment]
Thank you @drebbe-intrepid and @hollinsky-intrepid

**Pull request merged**
